import Head from 'next/head'
import PhotosGroup from "../components/PhotosGroup";
import { images } from "../static/images";

function groupImages(images) {
  let groupedImages = [];
  let cursor = [];
  let count = 0;

  for (let i = 0; i < images.length; i++) {
    cursor.push(images[i]);

    if (
      (count % 2 === 0 && cursor.length === 5) ||
      (count % 2 === 1 && cursor.length === 3)
    ) {
      groupedImages.push(cursor);
      cursor = [];
      count++;
    }
  }

  groupedImages.push(cursor);

  return groupedImages;
}

export default function Home() {
  const grouped = groupImages(images);
  return (
    <div className="px-6 md:px-10 lg:px-16 xl:px-20 py-14">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {grouped.map((group, i) => (
        <PhotosGroup key={i} swaped={i % 2 === 0} images={group} />
      ))}
      {/* trick JIT */}
      <div className="hidden flex-row-reverse w-1/2"></div>
    </div>
  );
}
